

query ListOrganisations
  @auth(level: PUBLIC) {
  organisations {
    id
    prCode
    organisationName
    district
    state
    pinCode
    phone
    email
    website
    actionStatus
    workingStatus
  }
}

query SearchOrganisations(
  $prCode: String
  $organisationName: String
  $district: String
  $state: String
  $actionStatus: String
  $workingStatus: Boolean
  $limit: Int = 25
  $offset: Int = 0
)
  @auth(level: PUBLIC) {
  organisations(
    where: {
      _and: [
        { prCode: { contains: $prCode } }
        { organisationName: { contains: $organisationName } }
        { district: { contains: $district } }
        { state: { contains: $state } }
        { actionStatus: { contains: $actionStatus } }
        { workingStatus: { eq: $workingStatus } }
      ]
    }
    orderBy: [{ organisationName: ASC }, { prCode: ASC }]
    limit: $limit
    offset: $offset
  ) {
    id
    prCode
    organisationName
    district
    state
    pinCode
    phone
    email
    website
    actionStatus
    workingStatus
  }
}

query GetOrganisationByPrCode($prCode: String!)
  @auth(level: PUBLIC) {
  organisations(where: { prCode: { eq: $prCode } }) {
    id
    prCode
    groupCode
    ptCode
    organisationName
    address
    district
    state
    pinCode
    phone
    email
    website
    actionStatus
    remark
    academicYear
    strength
    boardType
    sessionStartFrom
    minorityType
    saturdayStatus
    workingStatus
  }
}


query ListBooksellers
  @auth(level: PUBLIC) {
  booksellers {
    id
    booksellerCode
    booksellerSubCode
    booksellerName
    district
    state
    pinCode
    contactNumber
    email
    vendorType
  }
}

query GetBooksellerByCode($booksellerCode: String!)
  @auth(level: PUBLIC) {
  booksellers(where: { booksellerCode: { eq: $booksellerCode } }) {
    id
    booksellerCode
    booksellerSubCode
    booksellerName
    academicYear
    address01
    district
    state
    pinCode
    gstPin
    incumbentCode
    incumbentName
    contactNumber
    email
    vendorType
    remark
  }
}

query ListItems
@auth(level: PUBLIC){

items{
 id
 itemCode
 title
 categoryType
 languageCode
 mrp
 isbnNo
 obsolete
}

}
query GetItemByCode($itemCode:String!)
@auth(level: PUBLIC){

items(
where:{
itemCode:{
eq:$itemCode
}
}
){

id
itemCode
title
categoryType
categoryCode
subCategoryCode
languageCode
customisationType
customisationCode
editionCode
mrp
isbnNo
obsolete

}

}