extend type Mutation {
  """
  ✨ Insert a single `Bookseller` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  bookseller_insert(
    """
    Data object to insert into the table.
    """
    data: Bookseller_Data!
  ): Bookseller_KeyOutput! @fdc_generated(from: "Bookseller", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `BooksellerSchoolMapping` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  booksellerSchoolMapping_insert(
    """
    Data object to insert into the table.
    """
    data: BooksellerSchoolMapping_Data!
  ): BooksellerSchoolMapping_KeyOutput! @fdc_generated(from: "BooksellerSchoolMapping", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Item` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  item_insert(
    """
    Data object to insert into the table.
    """
    data: Item_Data!
  ): Item_KeyOutput! @fdc_generated(from: "Item", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Organisation` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  organisation_insert(
    """
    Data object to insert into the table.
    """
    data: Organisation_Data!
  ): Organisation_KeyOutput! @fdc_generated(from: "Organisation", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Bookseller` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  bookseller_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Bookseller_Data!]!
  ): [Bookseller_KeyOutput!]! @fdc_generated(from: "Bookseller", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `BooksellerSchoolMapping` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  booksellerSchoolMapping_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [BooksellerSchoolMapping_Data!]!
  ): [BooksellerSchoolMapping_KeyOutput!]! @fdc_generated(from: "BooksellerSchoolMapping", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Item` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  item_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Item_Data!]!
  ): [Item_KeyOutput!]! @fdc_generated(from: "Item", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Organisation` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  organisation_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Organisation_Data!]!
  ): [Organisation_KeyOutput!]! @fdc_generated(from: "Organisation", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Bookseller` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Bookseller`.
  """
  bookseller_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Bookseller_Data!
  ): Bookseller_KeyOutput! @fdc_generated(from: "Bookseller", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `BooksellerSchoolMapping` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `BooksellerSchoolMapping`.
  """
  booksellerSchoolMapping_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: BooksellerSchoolMapping_Data!
  ): BooksellerSchoolMapping_KeyOutput! @fdc_generated(from: "BooksellerSchoolMapping", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Item` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Item`.
  """
  item_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Item_Data!
  ): Item_KeyOutput! @fdc_generated(from: "Item", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Organisation` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Organisation`.
  """
  organisation_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Organisation_Data!
  ): Organisation_KeyOutput! @fdc_generated(from: "Organisation", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Bookseller` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Bookseller`.
  """
  bookseller_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Bookseller_Data!]!
  ): [Bookseller_KeyOutput!]! @fdc_generated(from: "Bookseller", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `BooksellerSchoolMapping` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `BooksellerSchoolMapping`.
  """
  booksellerSchoolMapping_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [BooksellerSchoolMapping_Data!]!
  ): [BooksellerSchoolMapping_KeyOutput!]! @fdc_generated(from: "BooksellerSchoolMapping", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Item` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Item`.
  """
  item_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Item_Data!]!
  ): [Item_KeyOutput!]! @fdc_generated(from: "Item", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Organisation` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Organisation`.
  """
  organisation_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Organisation_Data!]!
  ): [Organisation_KeyOutput!]! @fdc_generated(from: "Organisation", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Bookseller` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Bookseller` or `null` if not found.
  """
  bookseller_update(
    """
    The unique ID of the object.
    """
    id: Int64

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int64_Expr

    """
    The key used to identify the object.
    """
    key: Bookseller_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Bookseller_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Bookseller_Data!
  ): Bookseller_KeyOutput @fdc_generated(from: "Bookseller", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `BooksellerSchoolMapping` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `BooksellerSchoolMapping` or `null` if not found.
  """
  booksellerSchoolMapping_update(
    """
    The unique ID of the object.
    """
    id: Int64

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int64_Expr

    """
    The key used to identify the object.
    """
    key: BooksellerSchoolMapping_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: BooksellerSchoolMapping_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: BooksellerSchoolMapping_Data!
  ): BooksellerSchoolMapping_KeyOutput @fdc_generated(from: "BooksellerSchoolMapping", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Item` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Item` or `null` if not found.
  """
  item_update(
    """
    The unique ID of the object.
    """
    id: Int64

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int64_Expr

    """
    The key used to identify the object.
    """
    key: Item_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Item_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Item_Data!
  ): Item_KeyOutput @fdc_generated(from: "Item", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Organisation` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Organisation` or `null` if not found.
  """
  organisation_update(
    """
    The unique ID of the object.
    """
    id: Int64

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int64_Expr

    """
    The key used to identify the object.
    """
    key: Organisation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Organisation_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Organisation_Data!
  ): Organisation_KeyOutput @fdc_generated(from: "Organisation", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Bookseller` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  bookseller_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Bookseller_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Bookseller_Data!
  ): Int! @fdc_generated(from: "Bookseller", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `BooksellerSchoolMapping` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  booksellerSchoolMapping_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: BooksellerSchoolMapping_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: BooksellerSchoolMapping_Data!
  ): Int! @fdc_generated(from: "BooksellerSchoolMapping", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Item` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  item_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Item_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Item_Data!
  ): Int! @fdc_generated(from: "Item", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Organisation` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  organisation_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Organisation_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Organisation_Data!
  ): Int! @fdc_generated(from: "Organisation", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Bookseller` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  bookseller_delete(
    """
    The unique ID of the object.
    """
    id: Int64

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int64_Expr

    """
    The key used to identify the object.
    """
    key: Bookseller_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Bookseller_FirstRow
  ): Bookseller_KeyOutput @fdc_generated(from: "Bookseller", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `BooksellerSchoolMapping` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  booksellerSchoolMapping_delete(
    """
    The unique ID of the object.
    """
    id: Int64

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int64_Expr

    """
    The key used to identify the object.
    """
    key: BooksellerSchoolMapping_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: BooksellerSchoolMapping_FirstRow
  ): BooksellerSchoolMapping_KeyOutput @fdc_generated(from: "BooksellerSchoolMapping", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Item` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  item_delete(
    """
    The unique ID of the object.
    """
    id: Int64

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int64_Expr

    """
    The key used to identify the object.
    """
    key: Item_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Item_FirstRow
  ): Item_KeyOutput @fdc_generated(from: "Item", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Organisation` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  organisation_delete(
    """
    The unique ID of the object.
    """
    id: Int64

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int64_Expr

    """
    The key used to identify the object.
    """
    key: Organisation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Organisation_FirstRow
  ): Organisation_KeyOutput @fdc_generated(from: "Organisation", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Bookseller` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  bookseller_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Bookseller_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Bookseller", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `BooksellerSchoolMapping` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  booksellerSchoolMapping_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: BooksellerSchoolMapping_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "BooksellerSchoolMapping", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Item` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  item_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Item_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Item", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Organisation` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  organisation_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Organisation_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Organisation", purpose: DELETE_MULTIPLE)
}
