extend type Mutation {
  """
  ✨ Insert a single `Organisation` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  organisation_insert(
    """
    Data object to insert into the table.
    """
    data: Organisation_Data!
  ): Organisation_KeyOutput! @fdc_generated(from: "Organisation", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Organisation` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  organisation_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Organisation_Data!]!
  ): [Organisation_KeyOutput!]! @fdc_generated(from: "Organisation", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Organisation` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Organisation`.
  """
  organisation_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Organisation_Data!
  ): Organisation_KeyOutput! @fdc_generated(from: "Organisation", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Organisation` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Organisation`.
  """
  organisation_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Organisation_Data!]!
  ): [Organisation_KeyOutput!]! @fdc_generated(from: "Organisation", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Organisation` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Organisation` or `null` if not found.
  """
  organisation_update(
    """
    The unique ID of the object.
    """
    id: Int64

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int64_Expr

    """
    The key used to identify the object.
    """
    key: Organisation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Organisation_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Organisation_Data!
  ): Organisation_KeyOutput @fdc_generated(from: "Organisation", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Organisation` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  organisation_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Organisation_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Organisation_Data!
  ): Int! @fdc_generated(from: "Organisation", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Organisation` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  organisation_delete(
    """
    The unique ID of the object.
    """
    id: Int64

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int64_Expr

    """
    The key used to identify the object.
    """
    key: Organisation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Organisation_FirstRow
  ): Organisation_KeyOutput @fdc_generated(from: "Organisation", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Organisation` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  organisation_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Organisation_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Organisation", purpose: DELETE_MULTIPLE)
}
