extend type Bookseller {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Bookseller", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Bookseller` table.
  """
  _count: Int! @fdc_generated(from: "Bookseller.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Bookseller` table where the `academicYear` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  academicYear_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Bookseller.academicYear", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Bookseller` table where the `address01` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  address01_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Bookseller.address01", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Bookseller` table where the `booksellerCode` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  booksellerCode_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Bookseller.booksellerCode", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Bookseller` table where the `booksellerName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  booksellerName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Bookseller.booksellerName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Bookseller` table where the `booksellerSubCode` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  booksellerSubCode_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Bookseller.booksellerSubCode", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Bookseller` table where the `contactNumber` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  contactNumber_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Bookseller.contactNumber", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Bookseller` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Bookseller.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Bookseller` table where the `district` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  district_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Bookseller.district", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Bookseller` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Bookseller.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Bookseller` table where the `gstPin` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  gstPin_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Bookseller.gstPin", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Bookseller` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Bookseller.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Bookseller` table where the `incumbentCode` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  incumbentCode_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Bookseller.incumbentCode", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Bookseller` table where the `incumbentName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  incumbentName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Bookseller.incumbentName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Bookseller` table where the `pinCode` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  pinCode_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Bookseller.pinCode", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Bookseller` table where the `remark` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  remark_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Bookseller.remark", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Bookseller` table where the `sourceHash` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  sourceHash_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Bookseller.sourceHash", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Bookseller` table where the `sourceRow` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  sourceRow_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Bookseller.sourceRow", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Bookseller` table where the `state` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  state_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Bookseller.state", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Bookseller` table where the `syncedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  syncedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Bookseller.syncedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Bookseller` table where the `updatedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  updatedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Bookseller.updatedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Bookseller` table where the `vendorType` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  vendorType_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Bookseller.vendorType", purpose: QUERY_COUNT)
  """
  ✨ Sum the `id` field in the `Bookseller` table.
  """
  id_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int64 @fdc_generated(from: "Bookseller.id", purpose: QUERY_SUM)
  """
  ✨ Sum the `sourceRow` field in the `Bookseller` table.
  """
  sourceRow_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Bookseller.sourceRow", purpose: QUERY_SUM)
  """
  ✨ Average the `id` field in the `Bookseller` table.
  """
  id_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Bookseller.id", purpose: QUERY_AVG)
  """
  ✨ Average the `sourceRow` field in the `Bookseller` table.
  """
  sourceRow_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Bookseller.sourceRow", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `Bookseller` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Bookseller.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `id` field in the `Bookseller` table.
  """
  id_min: Int64 @fdc_generated(from: "Bookseller.id", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `sourceRow` field in the `Bookseller` table.
  """
  sourceRow_min: Int @fdc_generated(from: "Bookseller.sourceRow", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `syncedAt` field in the `Bookseller` table.
  """
  syncedAt_min: Timestamp @fdc_generated(from: "Bookseller.syncedAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `updatedAt` field in the `Bookseller` table.
  """
  updatedAt_min: Timestamp @fdc_generated(from: "Bookseller.updatedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Bookseller` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Bookseller.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `id` field in the `Bookseller` table.
  """
  id_max: Int64 @fdc_generated(from: "Bookseller.id", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `sourceRow` field in the `Bookseller` table.
  """
  sourceRow_max: Int @fdc_generated(from: "Bookseller.sourceRow", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `syncedAt` field in the `Bookseller` table.
  """
  syncedAt_max: Timestamp @fdc_generated(from: "Bookseller.syncedAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `updatedAt` field in the `Bookseller` table.
  """
  updatedAt_max: Timestamp @fdc_generated(from: "Bookseller.updatedAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Bookseller.id", purpose: ENTITY_ID)
}
extend type Item {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Item", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Item` table.
  """
  _count: Int! @fdc_generated(from: "Item.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Item` table where the `categoryCode` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  categoryCode_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Item.categoryCode", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Item` table where the `categoryType` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  categoryType_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Item.categoryType", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Item` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Item.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Item` table where the `customisationCode` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  customisationCode_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Item.customisationCode", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Item` table where the `customisationType` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  customisationType_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Item.customisationType", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Item` table where the `editionCode` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  editionCode_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Item.editionCode", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Item` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Item.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Item` table where the `isbnNo` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  isbnNo_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Item.isbnNo", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Item` table where the `itemCode` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  itemCode_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Item.itemCode", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Item` table where the `itemSerialNo` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  itemSerialNo_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Item.itemSerialNo", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Item` table where the `languageCode` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  languageCode_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Item.languageCode", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Item` table where the `mrp` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  mrp_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Item.mrp", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Item` table where the `obsolete` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  obsolete_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Item.obsolete", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Item` table where the `subCategoryCode` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  subCategoryCode_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Item.subCategoryCode", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Item` table where the `syncedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  syncedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Item.syncedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Item` table where the `title` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  title_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Item.title", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Item` table where the `updatedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  updatedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Item.updatedAt", purpose: QUERY_COUNT)
  """
  ✨ Sum the `id` field in the `Item` table.
  """
  id_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int64 @fdc_generated(from: "Item.id", purpose: QUERY_SUM)
  """
  ✨ Sum the `itemSerialNo` field in the `Item` table.
  """
  itemSerialNo_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Item.itemSerialNo", purpose: QUERY_SUM)
  """
  ✨ Sum the `mrp` field in the `Item` table.
  """
  mrp_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Item.mrp", purpose: QUERY_SUM)
  """
  ✨ Average the `id` field in the `Item` table.
  """
  id_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Item.id", purpose: QUERY_AVG)
  """
  ✨ Average the `itemSerialNo` field in the `Item` table.
  """
  itemSerialNo_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Item.itemSerialNo", purpose: QUERY_AVG)
  """
  ✨ Average the `mrp` field in the `Item` table.
  """
  mrp_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Item.mrp", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `Item` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Item.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `id` field in the `Item` table.
  """
  id_min: Int64 @fdc_generated(from: "Item.id", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `itemSerialNo` field in the `Item` table.
  """
  itemSerialNo_min: Int @fdc_generated(from: "Item.itemSerialNo", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `mrp` field in the `Item` table.
  """
  mrp_min: Float @fdc_generated(from: "Item.mrp", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `syncedAt` field in the `Item` table.
  """
  syncedAt_min: Timestamp @fdc_generated(from: "Item.syncedAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `updatedAt` field in the `Item` table.
  """
  updatedAt_min: Timestamp @fdc_generated(from: "Item.updatedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Item` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Item.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `id` field in the `Item` table.
  """
  id_max: Int64 @fdc_generated(from: "Item.id", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `itemSerialNo` field in the `Item` table.
  """
  itemSerialNo_max: Int @fdc_generated(from: "Item.itemSerialNo", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `mrp` field in the `Item` table.
  """
  mrp_max: Float @fdc_generated(from: "Item.mrp", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `syncedAt` field in the `Item` table.
  """
  syncedAt_max: Timestamp @fdc_generated(from: "Item.syncedAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `updatedAt` field in the `Item` table.
  """
  updatedAt_max: Timestamp @fdc_generated(from: "Item.updatedAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Item.id", purpose: ENTITY_ID)
}
extend type Organisation {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Organisation", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Organisation` table.
  """
  _count: Int! @fdc_generated(from: "Organisation.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Organisation` table where the `academicYear` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  academicYear_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Organisation.academicYear", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Organisation` table where the `actionStatus` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  actionStatus_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Organisation.actionStatus", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Organisation` table where the `address` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  address_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Organisation.address", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Organisation` table where the `boardType` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  boardType_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Organisation.boardType", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Organisation` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Organisation.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Organisation` table where the `district` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  district_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Organisation.district", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Organisation` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Organisation.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Organisation` table where the `groupCode` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  groupCode_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Organisation.groupCode", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Organisation` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Organisation.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Organisation` table where the `minorityType` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  minorityType_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Organisation.minorityType", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Organisation` table where the `organisationName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  organisationName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Organisation.organisationName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Organisation` table where the `phone` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  phone_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Organisation.phone", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Organisation` table where the `pinCode` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  pinCode_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Organisation.pinCode", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Organisation` table where the `prCode` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  prCode_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Organisation.prCode", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Organisation` table where the `ptCode` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  ptCode_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Organisation.ptCode", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Organisation` table where the `remark` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  remark_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Organisation.remark", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Organisation` table where the `saturdayStatus` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  saturdayStatus_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Organisation.saturdayStatus", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Organisation` table where the `sessionStartFrom` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  sessionStartFrom_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Organisation.sessionStartFrom", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Organisation` table where the `sourceHash` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  sourceHash_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Organisation.sourceHash", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Organisation` table where the `sourceSheetRow` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  sourceSheetRow_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Organisation.sourceSheetRow", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Organisation` table where the `state` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  state_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Organisation.state", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Organisation` table where the `strength` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  strength_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Organisation.strength", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Organisation` table where the `syncedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  syncedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Organisation.syncedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Organisation` table where the `updatedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  updatedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Organisation.updatedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Organisation` table where the `website` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  website_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Organisation.website", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Organisation` table where the `workingStatus` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  workingStatus_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Organisation.workingStatus", purpose: QUERY_COUNT)
  """
  ✨ Sum the `id` field in the `Organisation` table.
  """
  id_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int64 @fdc_generated(from: "Organisation.id", purpose: QUERY_SUM)
  """
  ✨ Sum the `sourceSheetRow` field in the `Organisation` table.
  """
  sourceSheetRow_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Organisation.sourceSheetRow", purpose: QUERY_SUM)
  """
  ✨ Sum the `strength` field in the `Organisation` table.
  """
  strength_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Organisation.strength", purpose: QUERY_SUM)
  """
  ✨ Average the `id` field in the `Organisation` table.
  """
  id_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Organisation.id", purpose: QUERY_AVG)
  """
  ✨ Average the `sourceSheetRow` field in the `Organisation` table.
  """
  sourceSheetRow_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Organisation.sourceSheetRow", purpose: QUERY_AVG)
  """
  ✨ Average the `strength` field in the `Organisation` table.
  """
  strength_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Organisation.strength", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `Organisation` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Organisation.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `id` field in the `Organisation` table.
  """
  id_min: Int64 @fdc_generated(from: "Organisation.id", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `sessionStartFrom` field in the `Organisation` table.
  """
  sessionStartFrom_min: Date @fdc_generated(from: "Organisation.sessionStartFrom", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `sourceSheetRow` field in the `Organisation` table.
  """
  sourceSheetRow_min: Int @fdc_generated(from: "Organisation.sourceSheetRow", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `strength` field in the `Organisation` table.
  """
  strength_min: Int @fdc_generated(from: "Organisation.strength", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `syncedAt` field in the `Organisation` table.
  """
  syncedAt_min: Timestamp @fdc_generated(from: "Organisation.syncedAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `updatedAt` field in the `Organisation` table.
  """
  updatedAt_min: Timestamp @fdc_generated(from: "Organisation.updatedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Organisation` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Organisation.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `id` field in the `Organisation` table.
  """
  id_max: Int64 @fdc_generated(from: "Organisation.id", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `sessionStartFrom` field in the `Organisation` table.
  """
  sessionStartFrom_max: Date @fdc_generated(from: "Organisation.sessionStartFrom", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `sourceSheetRow` field in the `Organisation` table.
  """
  sourceSheetRow_max: Int @fdc_generated(from: "Organisation.sourceSheetRow", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `strength` field in the `Organisation` table.
  """
  strength_max: Int @fdc_generated(from: "Organisation.strength", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `syncedAt` field in the `Organisation` table.
  """
  syncedAt_max: Timestamp @fdc_generated(from: "Organisation.syncedAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `updatedAt` field in the `Organisation` table.
  """
  updatedAt_max: Timestamp @fdc_generated(from: "Organisation.updatedAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Organisation.id", purpose: ENTITY_ID)
}
